# Generated by Django 3.1.6 on 2021-02-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='dateTime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
