# Generated by Django 3.1.6 on 2021-02-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSO', '0002_auto_20210204_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petrol',
            name='petrolType',
            field=models.CharField(choices=[(1, 'OR92'), (2, 'OR95'), (3, 'OR98'), (4, 'DIESEL')], max_length=30, verbose_name='Вид НП'),
        ),
        migrations.AlterField(
            model_name='pumpstate',
            name='status',
            field=models.CharField(choices=[(1, 'FREE'), (2, 'BUSY'), (3, 'UNAVAILABLE')], max_length=30, verbose_name='Статус ТРК'),
        ),
    ]
