# Generated by Django 3.1.6 on 2021-02-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSO', '0003_auto_20210204_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petrol',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='petrol',
            name='petrolType',
            field=models.CharField(choices=[('OR92', 'OR92'), ('OR95', 'OR95'), ('OR98', 'OR98'), ('DIESEL', 'DIESEL')], max_length=30, verbose_name='Вид НП'),
        ),
        migrations.AlterField(
            model_name='pumpstate',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pumpstate',
            name='status',
            field=models.CharField(choices=[('FREE', 'FREE'), ('BUSY', 'BUSY'), ('UNAVAILABLE', 'UNAVAILABLE')], max_length=30, verbose_name='Статус ТРК'),
        ),
    ]
