# Generated by Django 3.1.6 on 2021-02-05 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TSO', '0004_auto_20210204_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField()),
                ('dateTime', models.DateTimeField(db_index=True)),
                ('orderType', models.CharField(choices=[('PETROL', 'PETROL'), ('OTHER', 'OTHER')], max_length=20, verbose_name='Тип заказа')),
                ('barCode', models.CharField(max_length=30, unique=True, verbose_name='Штрих-код')),
                ('terminalNumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TSO.terminal', verbose_name='Номер Терминала')),
            ],
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('orderId', 'terminalNumber'), name='uniqueId'),
        ),
    ]
