# Generated by Django 3.1.6 on 2021-02-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TSO', '0006_auto_20210205_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpetrol',
            name='change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TSO.orderother', verbose_name='Перевод сдачи'),
        ),
    ]
