# Generated by Django 3.1.6 on 2021-02-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSO', '0007_auto_20210205_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherType', models.CharField(choices=[('MTS', 'MTS'), ('TELE2', 'TELE2'), ('BEELINE', 'BEELINE'), ('MEGAFON', 'MEGAFON'), ('EWALLET', 'EWALLET')], max_length=20, unique=True, verbose_name='Тип услуги')),
            ],
        ),
    ]
