# Generated by Django 3.1.6 on 2021-02-05 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TSO', '0008_othertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderother',
            name='amount',
            field=models.FloatField(default=1, verbose_name='Снято'),
        ),
        migrations.AddField(
            model_name='orderother',
            name='cash',
            field=models.FloatField(default=1, verbose_name='Остаток'),
        ),
        migrations.AddField(
            model_name='orderother',
            name='change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TSO.orderother', verbose_name='Перевод сдачи'),
        ),
        migrations.AddField(
            model_name='orderother',
            name='fromId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='order0', to='TSO.order', verbose_name='Предыдущий заказ'),
        ),
        migrations.AddField(
            model_name='orderother',
            name='number',
            field=models.CharField(default='1', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='orderother',
            name='orderId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='order1', to='TSO.order', verbose_name='Номер заказа'),
        ),
        migrations.AddField(
            model_name='orderother',
            name='otherType',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='TSO.othertype', verbose_name='Тип услуги'),
        ),
    ]
