# Generated by Django 3.1.6 on 2021-02-05 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TSO', '0009_auto_20210205_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderother',
            name='amount',
            field=models.FloatField(verbose_name='Снято'),
        ),
        migrations.AlterField(
            model_name='orderother',
            name='cash',
            field=models.FloatField(verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='orderother',
            name='fromId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order0', to='TSO.order', verbose_name='Предыдущий заказ'),
        ),
        migrations.AlterField(
            model_name='orderother',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='orderother',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order1', to='TSO.order', verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='orderother',
            name='otherType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TSO.othertype', verbose_name='Тип услуги'),
        ),
    ]
