# Generated by Django 3.1.6 on 2021-02-05 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TSO', '0010_auto_20210205_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(db_index=True)),
                ('terminalNumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TSO.terminal', verbose_name='Номер Терминала')),
            ],
        ),
    ]
