# Generated by Django 3.1.6 on 2021-02-06 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TSO', '0011_datetimeterminal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderother',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderother',
            name='fromId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order0', to='TSO.order', verbose_name='Предыдущий заказ'),
        ),
        migrations.AlterField(
            model_name='orderother',
            name='orderId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='order1', serialize=False, to='TSO.order', verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='orderpetrol',
            name='orderId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='TSO.order', verbose_name='Номер заказа'),
        ),
    ]
