# Generated by Django 3.1.6 on 2021-02-06 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TSO', '0012_auto_20210206_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpetrol',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderother',
            name='orderId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='order1', serialize=False, to='TSO.order', verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='orderpetrol',
            name='orderId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TSO.order', verbose_name='Номер заказа'),
        ),
    ]
