# Generated by Django 3.1.6 on 2021-02-06 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TSO', '0013_auto_20210206_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errortype',
            name='errortype',
            field=models.CharField(choices=[('OK', 'OK'), ('SCANER', 'SCANER'), ('PAPER', 'PAPER'), ('CURRENCYDETECTOR', 'CURRENCYDETECTOR'), ('INK', 'INK'), ('POS', 'POS'), ('OTHER', 'OTHER')], max_length=50, unique=True, verbose_name='Ограничения ТСО'),
        ),
        migrations.AlterField(
            model_name='pumpstate',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSO.pump', verbose_name='Номер ТРК'),
        ),
    ]
